name: Promote Python Package

on:
  workflow_dispatch:

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'production'
  CLOUDSMITH_PRODUCTION_REPO: 'staging'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_NAME: 'example_package'

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Get package identifier and promote
        run: |
          # Query for the package and get its identifier
          PACKAGE_QUERY="filename:${PACKAGE_NAME}-${{ github.event.inputs.package_version }}.tar.gz"
          echo "Searching for package with query: $PACKAGE_QUERY"
          
